# Generated by Django 4.2 on 2023-05-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0003_crop_crop_image_variety_variety_image_grower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grower',
        ),
    ]
