# Generated by Django 4.2 on 2023-05-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0005_grower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grower',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='crop_id',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='Grower',
        ),
    ]
