# Generated by Django 4.2 on 2023-05-10 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0006_remove_grower_admin_remove_grower_crop_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plant_type', models.CharField(max_length=50)),
                ('soil_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('crop_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('variety_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seed.variety')),
            ],
        ),
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_number', models.CharField(max_length=12)),
                ('pan_number', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seed.crop')),
            ],
        ),
    ]
