# Generated by Django 4.2 on 2023-05-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0007_crop_grower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grower',
            name='crop_id',
        ),
    ]
