# Generated by Django 4.2 on 2023-05-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0012_state_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grower',
        ),
    ]
