# Generated by Django 4.2 on 2023-05-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0014_grower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
    ]
