# Generated by Django 4.2 on 2023-05-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0015_remove_city_state_remove_state_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='variety_id',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='state_id',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='Grower',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Variety',
        ),
    ]
