# Generated by Django 4.2 on 2023-05-12 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0018_grower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('from_date', models.DateField(auto_now_add=True)),
                ('to_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('yield_per_acre', models.CharField(max_length=50)),
                ('maturity_duration', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('variety_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plant_type', models.CharField(max_length=50)),
                ('soil_type', models.CharField(max_length=50)),
                ('cultivation_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('crop_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('maturity_date', models.DateField(auto_now_add=True)),
                ('sowing_date', models.DateField(auto_now_add=True)),
                ('area', models.CharField(max_length=50)),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seed.season')),
                ('variety_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seed.variety')),
            ],
        ),
    ]
