# Generated by Django 4.2 on 2023-05-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0019_season_variety_crop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grower',
        ),
    ]
