# Generated by Django 4.2 on 2023-05-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0021_grower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='maturity_duration',
            field=models.DateField(),
        ),
    ]
