# Generated by Django 4.2 on 2023-05-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0022_alter_season_from_date_alter_season_to_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='maturity_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='sowing_date',
            field=models.DateField(),
        ),
    ]
