# Generated by Django 4.2 on 2023-05-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0023_alter_crop_maturity_date_alter_crop_sowing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='maturity_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='sowing_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='from_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='to_date',
            field=models.DateField(blank=True),
        ),
    ]
