# Generated by Django 4.2 on 2023-05-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0025_alter_season_from_date_alter_season_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='season',
            name='to_date',
        ),
    ]
