# Generated by Django 4.2 on 2023-05-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0027_remove_crop_season_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='variety_id',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='crop_id',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='state_id',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='Grower',
        ),
        migrations.DeleteModel(
            name='Variety',
        ),
    ]
