# Generated by Django 4.2 on 2023-05-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0028_remove_crop_variety_id_remove_grower_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('from_date', models.CharField(max_length=50)),
            ],
        ),
    ]
