# Generated by Django 4.2 on 2023-05-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0029_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='from_date',
        ),
    ]
