# Generated by Django 4.2 on 2023-05-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0031_variety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='maturity_duration',
        ),
    ]
