# Generated by Django 4.2 on 2023-05-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0033_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='maturity_date',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='sowing_date',
        ),
    ]
