# Generated by Django 4.2 on 2023-05-14 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0035_grower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grower',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='crop_id',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='state_id',
        ),
        migrations.AddField(
            model_name='season',
            name='from_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='to_date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variety',
            name='maturity_duration',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='Grower',
        ),
    ]
