# Generated by Django 4.2 on 2023-05-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0036_remove_grower_admin_remove_grower_city_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='from_date',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='season',
            name='to_date',
            field=models.CharField(max_length=150),
        ),
    ]
