# Generated by Django 4.2 on 2023-05-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0039_grower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grower',
        ),
    ]
