# Generated by Django 4.2 on 2023-05-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0040_delete_grower'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='maturity_date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='sowing_date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
