# Generated by Django 4.2 on 2023-05-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0043_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grower_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_image', models.ImageField(upload_to='media/examinationimage')),
                ('grower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seed.grower')),
            ],
        ),
    ]
