# Generated by Django 4.2 on 2023-05-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0044_grower_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='grower',
            name='examination_image',
            field=models.ImageField(default=1, upload_to='media/examinationimage'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Grower_new',
        ),
    ]
