# Generated by Django 4.2 on 2023-05-29 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0045_grower_examination_image_delete_grower_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('pin', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_person',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Field_worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.TextField()),
                ('dob', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seed.agency')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seed.branch')),
                ('grower_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seed.grower')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='agency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seed.agency'),
        ),
        migrations.AddField(
            model_name='branch',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seed.city'),
        ),
        migrations.AddField(
            model_name='branch',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seed.country'),
        ),
        migrations.AddField(
            model_name='branch',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seed.state'),
        ),
    ]
