# Generated by Django 4.2 on 2023-05-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0046_branch_agency_contact_person_field_worker_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Field_worker',
        ),
    ]
