# Generated by Django 4.2 on 2023-05-30 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0047_delete_field_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field_worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.TextField()),
                ('dob', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seed.agency')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seed.branch')),
                ('grower_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seed.grower')),
            ],
        ),
    ]
