# Generated by Django 4.2 on 2023-05-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0048_field_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field_worker',
            name='grower_id',
        ),
    ]
