# Generated by Django 4.2 on 2023-05-30 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0049_remove_field_worker_grower_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='field_worker',
            name='grower_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='seed.grower'),
            preserve_default=False,
        ),
    ]
