# Generated by Django 4.2 on 2023-05-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0050_field_worker_grower_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field_worker',
            name='grower_id',
        ),
    ]
