# Generated by Django 4.2 on 2023-05-31 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0052_field_worker_grower_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grower',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seed.city'),
        ),
        migrations.AlterField(
            model_name='grower',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seed.country'),
        ),
        migrations.AlterField(
            model_name='grower',
            name='crop_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seed.crop'),
        ),
        migrations.AlterField(
            model_name='grower',
            name='state_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seed.state'),
        ),
    ]
