# Generated by Django 4.2 on 2023-06-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0053_alter_grower_city_id_alter_grower_country_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field_worker',
            name='grower_id',
            field=models.CharField(max_length=50),
        ),
    ]
