# Generated by Django 4.2 on 2023-06-02 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0054_alter_field_worker_grower_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field_worker',
            old_name='grower_id',
            new_name='grower',
        ),
    ]
